# Generated by Django 5.0.6 on 2025-02-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(max_length=100),
        ),
    ]
