# Generated by Django 5.0.6 on 2025-02-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
