# Generated by Django 5.0.6 on 2025-02-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0005_cow_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='cow',
            name='transaction_status',
            field=models.CharField(choices=[('available', 'พร้อมขาย'), ('pending', 'รอการยืนยัน'), ('sold', 'ขายสำเร็จ')], default='available', max_length=10),
        ),
    ]
