# Generated by Django 5.0.6 on 2025-02-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0006_remove_cow_is_sold_cow_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='transaction_status',
            field=models.CharField(choices=[('available', 'พร้อมขาย'), ('pending', 'รอการยืนยัน'), ('sold', 'ขายสำเร็จ')], default='available', max_length=20),
        ),
    ]
