# Generated by Django 5.1.1 on 2025-02-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0007_alter_cow_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
